server:
  port: 8082

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:payflow_wallets}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:payflow_user}
    password: ${MYSQL_PASSWORD:payflow_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET:payflow-super-secret-key-that-is-at-least-64-characters-long-for-hs512}

management:
  endpoints:
    web:
      exposure:
        include: health,info
