server:
  port: 8083

spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:payflow_transfers}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:payflow_user}
    password: ${MYSQL_PASSWORD:payflow_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET:payflow-super-secret-key-that-is-at-least-64-characters-long-for-hs512}

services:
  wallet-url: ${WALLET_SERVICE_URL:http://localhost:8082}
  transaction-url: ${TRANSACTION_SERVICE_URL:http://localhost:8084}

aws:
  sqs:
    queue-url: ${SQS_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/150506369517/payflow-transfers}

management:
  endpoints:
    web:
      exposure:
        include: health,info
